export const CREATE_CONTACT = 'CREATE_CONTACT';
export const GET_CONTACT = 'GET_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SELECT_ALL_CONTACT = 'SELECT_ALL_CONTACT';
export const CLEAR_ALL_CONTACT = 'CLEAR_ALL_CONTACT';
export const DELETE_ALL_CONTACT = 'DELETE_ALL_CONTACT';
